title: cjaccino test page
#email: cjaccino@gmail.com
description: A test page
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
#twitter_username:
#github_username:  
#google_analytics: 

# Build settings
markdown: kramdown
theme: minima
